services:
    ak76.sortable_behavior.position_handler:
        class: Ak76\SortableBehaviorBundle\Service\PositionHandler
        arguments:
            - @doctrine.orm.entity_manager
            - @property_accessor
